# -*- coding: utf-8 -*-
"""models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/189FHQr3w5IQmYv9ESVS7VN8kK5bS7quE
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

"""Basic Building Block"""

class ConvBNReLU(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size=3, stride=1, padding=1):
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, kernel_size, stride, padding, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True)
        )

    def forward(self, x):
        return self.block(x)

"""Detail Branch (High Resolution spatial features)"""

class DetailBranch(nn.Module):
    def __init__(self):
        super().__init__()
        self.stage1 = ConvBNReLU(3, 64, stride=2)
        self.stage2 = ConvBNReLU(64, 64)
        self.stage3 = ConvBNReLU(64, 128, stride=2)

    def forward(self, x):
        x = self.stage1(x)
        x = self.stage2(x)
        x = self.stage3(x)
        return x

"""Semantic Branch (Low resolution, high level semantics)"""

class SemanticBranch(nn.Module):
    def __init__(self):
        super().__init__()
        self.stage1 = ConvBNReLU(3, 32, stride=2)
        self.stage2 = ConvBNReLU(32, 64, stride=2)
        self.stage3 = ConvBNReLU(64, 128, stride=2)

    def forward(self, x):
        x = self.stage1(x)
        x = self.stage2(x)
        x = self.stage3(x)
        return x

"""Baseline BiSeNetV2 Model"""

class BiSeNetV2_Baseline(nn.Module):
    def __init__(self, num_classes=12):
        super().__init__()
        self.detail = DetailBranch()
        self.semantic = SemanticBranch()

        # Output head (baseline, unchanged)
        self.conv_out = nn.Conv2d(128, num_classes, kernel_size=1)

    def forward(self, x):
        h, w = x.size()[2:]

        feat_detail = self.detail(x)
        feat_semantic = self.semantic(x)

        # Upsample semantic branch to match detail branch
        feat_semantic_up = F.interpolate(
            feat_semantic,
            size=feat_detail.size()[2:],
            mode='bilinear',
            align_corners=True
        )

        fuse = feat_detail + feat_semantic_up
        out = self.conv_out(fuse)

        return F.interpolate(out, size=(h, w), mode='bilinear', align_corners=True)

"""Global Context Block ( IMPROVEMENT)"""

class GlobalContextBlock(nn.Module):
    def __init__(self, in_channels):
        super().__init__()
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.conv = nn.Sequential(
            nn.Conv2d(in_channels, in_channels, kernel_size=1),
            nn.Sigmoid()
        )

    def forward(self, x):
        context = self.avg_pool(x)
        context = self.conv(context)
        return x * context

"""Improved BiSeNetV2 (inherits Baseline)"""

class BiSeNetV2_Improved(BiSeNetV2_Baseline):
    def __init__(self, num_classes=12):
        super().__init__(num_classes)

        # Single, clear architecture improvement
        self.gc_block = GlobalContextBlock(128)

    def forward(self, x):
        h, w = x.size()[2:]

        feat_detail = self.detail(x)
        feat_semantic = self.semantic(x)

        # Apply global context enhancement
        feat_semantic = self.gc_block(feat_semantic)

        feat_semantic_up = F.interpolate(
            feat_semantic,
            size=feat_detail.size()[2:],
            mode='bilinear',
            align_corners=True
        )

        fuse = feat_detail + feat_semantic_up
        out = self.conv_out(fuse)

        return F.interpolate(out, size=(h, w), mode='bilinear', align_corners=True)

